### ISSUE TITLE
Can't activate Addon in Blender 2.79b

### ISSUE THREAD

**Issue by mrjumpingjack** [taniwha/io_object_mu#16]
Traceback (most recent call last):
  File "C:\Program Files\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Program Files\Blender\2.79\scripts\addons\io_object_mu-master\__init__.py", line 73, in register
    register_submodules(__name__, submodule_names);
  File "C:\Program Files\Blender\2.79\scripts\addons\io_object_mu-master\__init__.py", line 54, in register_submodules
    module = __import__(name=name, fromlist=submodule_names)
  File "C:\Program Files\Blender\2.79\scripts\addons\io_object_mu-master\collider\__init__.py", line 24, in <module>
    from .collider import create_collider_object, build_collider, update_collider
  File "C:\Program Files\Blender\2.79\scripts\addons\io_object_mu-master\collider\collider.py", line 28, in <module>
    from .. import properties
  File "C:\Program Files\Blender\2.79\scripts\addons\io_object_mu-master\properties\__init__.py", line 24, in <module>
    from .properties import dir_items, dir_map, SetPropMask, GetPropMask
  File "C:\Program Files\Blender\2.79\scripts\addons\io_object_mu-master\properties\properties.py", line 28
    spring: FloatProperty(name = "Spring")
          ^
SyntaxError: invalid syntax

**Comment by taniwha** [comment]
You need to check out the blender2.79 branch: git checkout blender2.79
Or you can switch to the blender2.79 branch on the github page and then download the zip.

**Comment by taniwha** [comment]
Actually, dots in directory names causing problems is a python issue, there's not a lot blender can do about it.
