### ISSUE TITLE
Python error importing model

### ISSUE THREAD

**Issue by linuxgurugamer** [taniwha/io_object_mu#23]
Read prefs: C:\Users\jbb\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.80\python
Info: Deleted 1 object(s)

Info: Deleted 1 object(s)

Info: Deleted 1 object(s)

Info: Deleted 1 object(s)

Info: Deleted 1 object(s)

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\operators.py", line 76, in execute
    return import_mu_op(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\operators.py", line 37, in import_mu_op
    ret = import_mu(collection, filepath, create_colliders, force_armature)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\import_mu.py", line 182, in import_mu
    return process_mu(mu, os.path.dirname(filepath)), mu
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\import_mu.py", line 170, in process_mu
    return create_object(mu, mu.obj, None)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\import_mu.py", line 154, in create_object
    create_object(mu, child, obj)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\import_mu.py", line 157, in create_object
    create_action(mu, muobj.path, clip)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\animation.py", line 152, in create_action
    fcurve = create_fcurve(act, curve, fullpropmap)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\animation.py", line 81, in create_fcurve
    fc = action.fcurves.new(data_path = dp, index = ind)
RuntimeError: Error: F-Curve 'mumatprop.color.properties[0].value[0]' already exists in action 'model6.obj'

location: <unknown location>:-1

location: <unknown location>:-1
Info: Deleted 1 object(s)

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\operators.py", line 76, in execute
    return import_mu_op(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\operators.py", line 37, in import_mu_op
    ret = import_mu(collection, filepath, create_colliders, force_armature)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\import_mu.py", line 182, in import_mu
    return process_mu(mu, os.path.dirname(filepath)), mu
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\import_mu.py", line 170, in process_mu
    return create_object(mu, mu.obj, None)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\import_mu.py", line 154, in create_object
    create_object(mu, child, obj)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\import_mu.py", line 157, in create_object
    create_action(mu, muobj.path, clip)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\animation.py", line 152, in create_action
    fcurve = create_fcurve(act, curve, fullpropmap)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\io_object_mu\import_mu\animation.py", line 81, in create_fcurve
    fc = action.fcurves.new(data_path = dp, index = ind)
RuntimeError: Error: F-Curve 'mumatprop.color.properties[0].value[0]' already exists in action 'model6.obj'

location: <unknown location>:-1

location: <unknown location>:-1

[Minuteman.zip](https://github.com/taniwha/io_object_mu/files/3624081/Minuteman.zip)

**Comment by taniwha** [comment]
The root cause of problem is the animation data in the model is quadruply redundant: Each of the four nozzles has curves for the emission property of the material attached to the nozzles. However, there is only one material (model6) that is shared between the 4 nozzels (it is shared even in KSP, not just in the .mu or blender). Thus when the importer got to the second nozzle being processed for animation data, it tried to add a duplicate curve to the material's animation data.

You'll get redundant NLA strips on the material.
