### ISSUE TITLE
craft import crash

### ISSUE THREAD

**Issue by AlexanderLieret** [taniwha/io_object_mu#24]
When importing my .craft file blender crashes. If I import the MK2 lander can, I get the same error messages but blender does not crash.

[craft.zip](https://github.com/taniwha/io_object_mu/files/4433250/craft.zip)

**Crashlog:**
$ blender
Read prefs: /home/alexander/.config/blender/2.80/config/userpref.blend
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1604 RNA_def_property_ui_text: 'Type of exported models when unspecified by root object.' description from 'modelType' '' ends with a '.' !
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1604 RNA_def_property_ui_text: 'Root object of the KSP internal model. Used for prop placement.' description from 'internal' '' ends with a '.' !
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1196 RNA_def_struct_ui_text: 'Create a convex hull from an object.' description from 'MESH_OT_quickhull' '' ends with a '.' !
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1604 RNA_def_property_ui_text: 'Create a convex hull from the raw mesh.' description from 'convex' '' ends with a '.' !
Registering panel class: 'IMAGE_PT_MuImagePanel' misses category, please update the script
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1196 RNA_def_struct_ui_text: 'Import a KSP .mu model as a prop.' description from 'IMPORT_OBJECT_OT_ksp_mu_prop' '' ends with a '.' !
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1196 RNA_def_struct_ui_text: 'Make KSP props from selected objects.' description from 'OBJECT_OT_make_ksp_props' '' ends with a '.' !
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1196 RNA_def_struct_ui_text: 'Add a KSP internal space prop instance.' description from 'OBJECT_OT_add_ksp_prop' '' ends with a '.' !
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1196 RNA_def_struct_ui_text: 'Import a KSP .craft (ship) file.' description from 'IMPORT_OBJECT_OT_ksp_craft' '' ends with a '.' !
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1196 RNA_def_struct_ui_text: 'Apply scale recursively without affecting parent inverse matrix.' description from 'OBJECT_OT_mu_apply_scale' '' ends with a '.' !
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1604 RNA_def_property_ui_text: 'Recurse object hierarchy.' description from 'recursive' '' ends with a '.' !
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1196 RNA_def_struct_ui_text: 'Clear parent inverse matrix keeping world transform.' description from 'OBJECT_OT_mu_clearinverse' '' ends with a '.' !
WARN (rna.define): /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/makesrna/intern/rna_define.c:1196 RNA_def_struct_ui_text: 'Import a KSP .mu model.' description from 'IMPORT_OBJECT_OT_ksp_mu' '' ends with a '.' !
Writing userprefs: '/home/alexander/.config/blender/2.80/config/userpref.blend' ok
Info: Color palettes created.

Info: Deleted 3 object(s)

model:Squad/Parts/Command/mk2LanderCan_v2/mk2LanderCan
Unknown shader: 'KSP/Alpha/Cutoff'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
model:Squad/Parts/Utility/dockingPort/model
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
model:Squad/Parts/FuelTank/RockomaxTanks/Assets/Rockomax8
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
model:Squad/Parts/Engine/liquidEngineLV-909_v2/TerrierV2
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
model:Squad/Parts/Coupling/Assets/Decoupler_1
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
model:Squad/Parts/Utility/landingLegLT-1/model
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
model:Squad/Parts/CompoundParts/strutConnector/model
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
model:Squad/Parts/Utility/ladderTelescopicBay/model
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
Unknown path: TelescopicLadderBay/Telescopic ladder/ChamferBox001
model:Squad/Parts/Utility/commDish88-88/model
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Location" not found'
Exception in node setup code:
Traceback (most recent call last):
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 415, in build_shader
    node_settex(name, mat.mumatprop, nodes, s)
  File "/home/alexander/.config/blender/2.80/scripts/addons/io_object_mu-master/shader/shader.py", line 381, in node_settex
    exec(cmd, {}, locals())
  File "<string>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Scale" not found'
blender(BLI_system_backtrace+0x37) [0x560db1e098f7]
blender(ED_armature_ebone_roll_to_vector+0x330) [0x560db232d260]
blender(EditBone_align_roll_call+0x16) [0x560db1ee6e86]
blender(RNA_function_call+0x16) [0x560db1ed0bc6]
blender(+0x1448300) [0x560db1e95300]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyObject_FastCallKeywords+0xd7) [0x7fe388d3ef07]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6dfc3) [0x7fe388b4efc3]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x68a2) [0x7fe388b55c42]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x7794b) [0x7fe388b5894b]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6e015) [0x7fe388b4f015]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x1cde) [0x7fe388b5107e]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x7794b) [0x7fe388b5894b]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6e015) [0x7fe388b4f015]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x1cde) [0x7fe388b5107e]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x7794b) [0x7fe388b5894b]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6e015) [0x7fe388b4f015]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x1cde) [0x7fe388b5107e]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x7794b) [0x7fe388b5894b]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6e015) [0x7fe388b4f015]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x1cde) [0x7fe388b5107e]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0x92d) [0x7fe388c774dd]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x89) [0x7fe388d3e5c9]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6e015) [0x7fe388b4f015]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x1cde) [0x7fe388b5107e]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x7794b) [0x7fe388b5894b]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x2c8) [0x7fe388d3e9b8]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyObject_Call_Prepend+0xcd) [0x7fe388d4027d]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x202476) [0x7fe388ce3476]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x20cd05) [0x7fe388cedd05]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyObject_FastCallKeywords+0xd7) [0x7fe388d3ef07]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6dfc3) [0x7fe388b4efc3]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x1cde) [0x7fe388b5107e]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x7794b) [0x7fe388b5894b]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6e015) [0x7fe388b4f015]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x242d) [0x7fe388b517cd]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x7794b) [0x7fe388b5894b]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6e015) [0x7fe388b4f015]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x1cde) [0x7fe388b5107e]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x7794b) [0x7fe388b5894b]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6e015) [0x7fe388b4f015]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x242d) [0x7fe388b517cd]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x7794b) [0x7fe388b5894b]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x6e015) [0x7fe388b4f015]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x1cde) [0x7fe388b5107e]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0x92d) [0x7fe388c774dd]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x12f) [0x7fe388d3e81f]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x2af5) [0x7fe388b51e95]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(+0x7794b) [0x7fe388b5894b]
/lib/x86_64-linux-gnu/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x2c8) [0x7fe388d3e9b8]
blender(+0x1448ffd) [0x560db1e95ffd]
blender(+0x15ae909) [0x560db1ffb909]
blender(+0x15bfeb3) [0x560db200ceb3]
blender(+0x15c278a) [0x560db200f78a]
blender(+0x15c438c) [0x560db201138c]
blender(wm_event_do_handlers+0x4fd) [0x560db2011bfd]
blender(WM_main+0x20) [0x560db2006db0]
blender(main+0x2b6) [0x560db1b85446]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fe384b3e1e3]
blender(_start+0x2e) [0x560db1bbda1e]
BLI_assert failed: /build/blender-ydgaLT/blender-2.80+dfsg/source/blender/editors/armature/armature_edit.c:211, ED_armature_ebone_roll_to_vector(), at '!(fabsf(_test_unit - 1.0f) >= 0.0002f) || !(fabsf(_test_unit) >= 0.0002f)'
[1]    17724 abort (core dumped)  blender

**Comment by AlexanderLieret** [comment]
I found the error. My blender installation was too old.
