### ISSUE TITLE
ReferenceError: StructRNA of type Collection has been removed 

### ISSUE THREAD

**Issue by taniwha** [taniwha/io_object_mu#26]
```
 Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_object_mu-master\import_craft\import_craft.py", line 106, in execute
    return import_craft_op(self, context, **keywords)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_object_mu-master\import_craft\import_craft.py", line 80, in import_craft_op
    obj = import_craft(filepath)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_object_mu-master\import_craft\import_craft.py", line 60, in import_craft
    part = gamedata.parts[pname].get_model()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_object_mu-master\import_craft\part.py", line 70, in get_model
    Vector((1, 1, 1)) * scale)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\scripts\addons\io_object_mu-master\import_craft\part.py", line 76, in instantiate
    obj.instance_collection = self.model
ReferenceError: StructRNA of type Collection has been removed

location: <unknown location>:-1

bpy.ops.import_object.ksp_craft(filepath="C:\\Users\\Micro753\\Documents\\Dove.craft") 
```

**Comment by taniwha** [comment]
I've never seen this. I don't think I'll get too grumpy if I close the issue ;)

**Comment by MoonTiger14** [comment]
please fix
