### ISSUE TITLE
error on export .mu

### ISSUE THREAD

**Issue by Rodg88** [taniwha/io_object_mu#35]
Using newest version of .mu plugin, on blender 2.93. I create a new blend file, add an empty with cube child, apply a box collider to it, and try export the empty as an mu. Then I just get this error:
`Traceback (most recent call last):
  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\operators.py", line 81, in execute
    return export_mu(self, context, **keywords)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\operators.py", line 34, in export_mu
    mu = export.export_object (context.active_object, filepath)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\export.py", line 156, in export_object
    mu.obj = make_obj(mu, obj, "")

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\export.py", line 115, in make_obj
    return make_obj_core(mu, obj, path, muobj)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\export.py", line 104, in make_obj_core
    child = make_obj(mu, o, path)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\export.py", line 115, in make_obj
    return make_obj_core(mu, obj, path, muobj)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\export.py", line 104, in make_obj_core
    child = make_obj(mu, o, path)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\export.py", line 115, in make_obj
    return make_obj_core(mu, obj, path, muobj)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\export.py", line 84, in make_obj_core
    muobj = type_handlers[type(obj.data)](obj, muobj, mu)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\empty.py", line 63, in handle_empty
    export_collection(obj, muobj, mu)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\empty.py", line 53, in export_collection
    child = export.make_obj(mu, o, mu.path)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\export.py", line 115, in make_obj
    return make_obj_core(mu, obj, path, muobj)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\export.py", line 84, in make_obj_core
    muobj = type_handlers[type(obj.data)](obj, muobj, mu)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\mesh.py", line 316, in handle_mesh
    muobj.shared_mesh = make_mesh(mu, obj)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\mesh.py", line 234, in make_mesh
    mumesh = make_mumesh(mesh, submeshes, vertex_data, vertex_map, num_verts)

  File "D:\Blender\2.83\scripts\addons\io_object_mu\export_mu\mesh.py", line 204, in make_mumesh
    if tangents[0] != None:

IndexError: list index out of range`

**Comment by Rodg88** [comment]
The model exported when i removed the auto generated collider
