### ISSUE TITLE
Model fails to import

### ISSUE THREAD

**Issue by blowfishpro** [taniwha/io_object_mu#40]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/431472fe19703b47233dde4098b13a9c686f7a2d/Gamedata/Bluedog_DB/Parts/Titan/bluedog_LR87_11_Single.mu

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_object_mu\import_mu\operators.py", line 79, in execute
    return import_mu_op(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_object_mu\import_mu\operators.py", line 37, in import_mu_op
    ret = import_mu(collection, filepath, create_colliders, force_armature, force_mesh)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_object_mu\import_mu\import_mu.py", line 203, in import_mu
    return process_mu(mu, os.path.dirname(filepath)), mu
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_object_mu\import_mu\import_mu.py", line 188, in process_mu
    create_armatures(mu)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_object_mu\import_mu\import_mu.py", line 182, in create_armatures
    scan_for_skins(mu, mu.obj)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_object_mu\import_mu\import_mu.py", line 178, in scan_for_skins
    scan_for_skins(mu, child)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_object_mu\import_mu\import_mu.py", line 178, in scan_for_skins
    scan_for_skins(mu, child)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_object_mu\import_mu\import_mu.py", line 176, in scan_for_skins
    process_skins(mu, skins, obj.children)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_object_mu\import_mu\armature.py", line 210, in process_skins
    bones, roots, parents = find_bones(mu, skins, siblings)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_object_mu\import_mu\armature.py", line 147, in find_bones
    if b in siblings or b.parent in skins:
AttributeError: 'NoneType' object has no attribute 'parent'

location: <unknown location>:-1
```

**Comment by Olympic1** [comment]
I'm getting the same error when trying to open the stock .mu file of `'Drill-O-Matic' Mining Excavator`.
**Path**: `GameData\Squad\Parts\Resources\RadialDrill\TriBitDrill.mu`

**Comment by whyAREyouRUNNING-debug** [comment]
If this is blowfishpro (creator of the b9 mods) saying an issue, it needs to be seen.

**Comment by popos123** [comment]
> I'm getting the same error when trying to open the stock .mu file of `'Drill-O-Matic' Mining Excavator`. **Path**: `GameData\Squad\Parts\Resources\RadialDrill\TriBitDrill.mu`

YES, exactly, from all Stock and from DLC parts, this is only one part that doesn't work (TriBitDrill.mu) !!!!!
I propose that author should resolve this problem and make 100% of openable / exportable parts 😊

**Comment by popos123** [comment]
i was make an update, now all models from stock and popular mods are loaded correctly, only this piece of garbage TriBitDrill.mu have problem with animations:
![image](https://github.com/user-attachments/assets/eb197d25-7c95-44cf-8842-171a0155aba5)
maybe importing / exporting is ok but in this case the bones from armature is unconnected and is mess:
![image](https://github.com/user-attachments/assets/f0f16188-8ece-453d-93ed-31b1b75fe95e)
but, rest of parts is ok, for now i dont know how to fix this part, maybe @taniwha knows how to fix that
