### ISSUE TITLE
Error when importing mu models in 2.93

### ISSUE THREAD

**Issue by jkerman2000** [taniwha/io_object_mu#54]
Python: Traceback (most recent call last):
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu-master\import_mu\operators.py", line 79, in execute
    return import_mu_op(self, context, **keywords)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu-master\import_mu\operators.py", line 37, in import_mu_op
    ret = import_mu(collection, filepath, create_colliders, force_armature, force_mesh)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 203, in import_mu
    return process_mu(mu, os.path.dirname(filepath)), mu
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 186, in process_mu
    create_materials(mu)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 165, in create_materials
    mumat.material = make_shader(mumat, mu)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu-master\shader\shader.py", line 212, in make_shader
    return make_shader4(mumat, mu)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu-master\shader\shader.py", line 204, in make_shader4
    make_shader_prop(mumat.colorProperties, matprops.color.properties, ctx)
  File "C:\Users\dario\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu-master\shader\shader.py", line 162, in make_shader_prop
    item.__annotations__["value"][1]["update"](item, context)
TypeError: '_PropertyDeferred' object is not subscriptable

location: <unknown location>:-1

**Comment by Parzival-3141** [comment]
This should fix your issue #50
