### ISSUE TITLE
Bug: import fails with TypeError

### ISSUE THREAD

**Issue by hlydecker** [taniwha/io_object_mu#55]
On Windows 11, with Blender 2.93 installed in Documents: 

>
Python: Traceback (most recent call last):
  File "C:\Users\henry\Documents\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu\import_craft\import_craft.py", line 106, in execute
    return import_craft_op(self, context, **keywords)
  File "C:\Users\henry\Documents\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu\import_craft\import_craft.py", line 80, in import_craft_op
    obj = import_craft(filepath)
  File "C:\Users\henry\Documents\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu\import_craft\import_craft.py", line 44, in import_craft
    gamedata = GameData(Preferences().GameData)
  File "C:\Users\henry\Documents\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu\import_craft\gamedata.py", line 140, in __init__
    self.models = Model.Preloaded()
  File "C:\Users\henry\Documents\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu\model\model.py", line 95, in Preloaded
    preloaded[url] = Model(None, url)
  File "C:\Users\henry\Documents\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu\model\model.py", line 106, in __init__
    obj, mu = import_mu(model, path, False, False)
  File "C:\Users\henry\Documents\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu\import_mu\import_mu.py", line 199, in import_mu
    if not mu.read(filepath):
  File "C:\Users\henry\Documents\Blender Foundation\Blender\2.93\scripts\addons\io_object_mu\mu.py", line 1181, in read
    self.file = open(filepath, "rb")
TypeError: expected str, bytes or os.PathLike object, not NoneType

location: <unknown location>:-1
>

Somehow I'm getting a TypeError?

**Comment by hlydecker** [comment]
Line 1181 in mu.py

```python
    def read(self, filepath):
        self.materials = []
        self.textures = []
        self.file = open(filepath, "rb")
        self.magic, self.version = self.read_int(2)
        if (self.magic != MuEnum.MODEL_BINARY or self.version < 0
            or self.version > MuEnum.FILE_VERSION):
            return None
        self.name = self.read_string()
        #print("version: %d '%s'" % (self.version, self.name))
        self.obj = MuObject().read(self)
        #self.read_materials()
        #self.read_textures()
        del self.file
        return self
```

**Comment by hlydecker** [comment]
Never mind I was being silly; you have to restart blender....

```ascii
............................................________........................
....................................,.-‘”...................``~.,..................
.............................,.-”...................................“-.,............
.........................,/...............................................”:,........
.....................,?......................................................\,.....
.................../...........................................................,}....
................./......................................................,:`^`..}....
.............../...................................................,:”........./.....
..............?.....__.........................................:`.........../.....
............./__.(.....“~-,_..............................,:`........../........
.........../(_....”~,_........“~,_....................,:`........_/...........
..........{.._$;_......”=,_.......“-,_.......,.-~-,},.~”;/....}...........
...........((.....*~_.......”=-._......“;,,./`..../”............../............
...,,,___.\`~,......“~.,....................`.....}............../.............
............(....`=-,,.......`........................(......;_,,-”...............
............/.`~,......`-...............................\....../\...................
.............\`~.*-,.....................................|,./.....\,__...........
,,_..........}.>-._\...................................|..............`=~-,....
.....`=~-,_\_......`\,.................................\........................
...................`=~-,,.\,...............................\.......................
................................`:,,...........................`\..............__..
.....................................`=-,...................,%`>--==``.......
........................................_\..........._,-%.......`\...............
...................................,<`.._|_,-&``................`\..............
```
