### ISSUE TITLE
Craft import error "path:'' " in other words path is none

### ISSUE THREAD

**Issue by D3fa1t1** [taniwha/io_object_mu#57]
B3d 2.92

here is the full traceback

Python: Traceback (most recent call last):
  File "C:\Users\papea\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_object_mu-master\import_craft\import_craft.py", line 106, in execute
    return import_craft_op(self, context, **keywords)
  File "C:\Users\papea\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_object_mu-master\import_craft\import_craft.py", line 80, in import_craft_op
    obj = import_craft(filepath)
  File "C:\Users\papea\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_object_mu-master\import_craft\import_craft.py", line 44, in import_craft
    gamedata = GameData(Preferences().GameData)
  File "C:\Users\papea\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_object_mu-master\import_craft\gamedata.py", line 146, in __init__
    self.create_db()
  File "C:\Users\papea\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_object_mu-master\import_craft\gamedata.py", line 129, in create_db
    recurse_tree(self.root, self.build_db)
  File "C:\Users\papea\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_object_mu-master\import_craft\gamedata.py", line 29, in recurse_tree
    files = os.listdir(path)
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: '' (translation: The system cant find the given path:'')

location: <unknown location>:-1

**Comment by D3fa1t1** [comment]
turns out i didnt install it correctly.
