### ISSUE TITLE
Exporting error after resizing

### ISSUE THREAD

**Issue by 1000snowy** [taniwha/io_object_mu#63]
After I import my file and resize it (S and Z buttons) vertically and doing nothing else, I get this error when I try to export it.

```
Python: Traceback (most recent call last):
  File "C:\Users\ultro\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_object_mu-master\export_mu\operators.py", line 81, in execute
    return export_mu(self, context, **keywords)
  File "C:\Users\ultro\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_object_mu-master\export_mu\operators.py", line 34, in export_mu
    mu = export.export_object (context.active_object, filepath)
  File "C:\Users\ultro\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_object_mu-master\export_mu\export.py", line 181, in export_object
    anim_root_obj.animation = make_animations(mu, animations, anim_root)
  File "C:\Users\ultro\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_object_mu-master\export_mu\animation.py", line 296, in make_animations
    clip.curves.append(make_curve(mu, muobj, curve, path, typ))
  File "C:\Users\ultro\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_object_mu-master\export_mu\animation.py", line 172, in make_curve
    property, mult, ctyp = property_map[curve.data_path][curve.array_index]
KeyError: 'rotation_euler'

```

**Comment by 1000snowy** [comment]
This should be fixed via [PR/64](https://github.com/taniwha/io_object_mu/pull/64).
