### ISSUE TITLE
 I have a problem in Blender 3.4

### ISSUE THREAD

**Issue by Lilxany87** [taniwha/io_object_mu#73]
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_object_mu-master\import_craft\import_craft.py", line 106, in execute
    return import_craft_op(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_object_mu-master\import_craft\import_craft.py", line 80, in import_craft_op
    obj = import_craft(filepath)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_object_mu-master\import_craft\import_craft.py", line 44, in import_craft
    gamedata = GameData(Preferences().GameData)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_object_mu-master\import_craft\gamedata.py", line 146, in __init__
    self.create_db()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_object_mu-master\import_craft\gamedata.py", line 129, in create_db
    recurse_tree(self.root, self.build_db)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_object_mu-master\import_craft\gamedata.py", line 29, in recurse_tree
    files = os.listdir(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

**Comment by SledgeBear** [comment]
ive been having the same problem.

**Comment by SledgeBear** [comment]
so im thinking its a problem on the dev's side. it used to work for 3.3, but now it doesnt work at all.

**Comment by Ahartry** [comment]
I have the exact same problem, any update or solution?

**Comment by popos123** [comment]
should be working now, the best experience is for blender 3.6, 4.0, 4.1. The 4.2 i wasnt tested yet
