### ISSUE TITLE
mu file from DeepFreeze fails to import

### ISSUE THREAD

**Issue by JonnyOThan** [taniwha/io_object_mu#76]
[model.zip](https://github.com/taniwha/io_object_mu/files/12475406/model.zip)

This model file from deepfreeze cannot be imported with the blender plugin, but it works fine in unity and in-game.

```
Python: Traceback (most recent call last):
  File "C:\Users\Jon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_object_mu-master\import_mu\operators.py", line 79, in execute
    return import_mu_op(self, context, **keywords)
  File "C:\Users\Jon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_object_mu-master\import_mu\operators.py", line 37, in import_mu_op
    ret = import_mu(collection, filepath, create_colliders, force_armature, force_mesh)
  File "C:\Users\Jon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 203, in import_mu
    return process_mu(mu, os.path.dirname(filepath)), mu
  File "C:\Users\Jon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 186, in process_mu
    create_materials(mu)
  File "C:\Users\Jon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 165, in create_materials
    mumat.material = make_shader(mumat, mu)
  File "C:\Users\Jon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_object_mu-master\shader\shader.py", line 246, in make_shader
    return make_shader4(mumat, mu)
  File "C:\Users\Jon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_object_mu-master\shader\shader.py", line 242, in make_shader4
    make_shader_tex_prop(mu, mumat.textureProperties, matprops.texture.properties, ctx)
  File "C:\Users\Jon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_object_mu-master\shader\shader.py", line 202, in make_shader_tex_prop
    set_tex(mu, item, muprop[k], context)
  File "C:\Users\Jon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_object_mu-master\shader\shader.py", line 178, in set_tex
    dst.type = tex.type
TypeError: bpy_struct: item.attr = val: MuTextureProperties.type expected True/False or 0/1, not int

location: <unknown location>:-1


```

**Comment by popos123** [comment]
fixed in new pull request 🙃
