### ISSUE TITLE
Skinned mesh import errors

### ISSUE THREAD

**Issue by Rodg88** [taniwha/io_object_mu#81]
Some example mu files that don't import which I've recently come across, using blender 3.6.1LTS

A plain fixed panel solar panel that just deploys at one joint:
[bluedog_Mariner71_SolarPanel.zip](https://github.com/user-attachments/files/15901439/bluedog_Mariner71_SolarPanel.zip)
From:
https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/1.14-Development/Gamedata/Bluedog_DB/Parts/ProbeExpansion/Mariner

A fairly complicated model for an engine:
[bluedog_LR87_11.zip](https://github.com/user-attachments/files/15901450/bluedog_LR87_11.zip)
From:
https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/1.14-Development/Gamedata/Bluedog_DB/Parts/Titan

both with the error:
```
Python: Traceback (most recent call last):
  File "C:\Users\rodge\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_object_mu-master\import_mu\operators.py", line 79, in execute
    return import_mu_op(self, context, **keywords)
  File "C:\Users\rodge\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_object_mu-master\import_mu\operators.py", line 37, in import_mu_op
    ret = import_mu(collection, filepath, create_colliders, force_armature, force_mesh)
  File "C:\Users\rodge\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 203, in import_mu
    return process_mu(mu, os.path.dirname(filepath)), mu
  File "C:\Users\rodge\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 188, in process_mu
    create_armatures(mu)
  File "C:\Users\rodge\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 182, in create_armatures
    scan_for_skins(mu, mu.obj)
  File "C:\Users\rodge\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 178, in scan_for_skins
    scan_for_skins(mu, child)
  File "C:\Users\rodge\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 178, in scan_for_skins
    scan_for_skins(mu, child)
  File "C:\Users\rodge\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_object_mu-master\import_mu\import_mu.py", line 176, in scan_for_skins
    process_skins(mu, skins, obj.children)
  File "C:\Users\rodge\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_object_mu-master\import_mu\armature.py", line 210, in process_skins
    bones, roots, parents = find_bones(mu, skins, siblings)
  File "C:\Users\rodge\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_object_mu-master\import_mu\armature.py", line 147, in find_bones
    if b in siblings or b.parent in skins:
AttributeError: 'NoneType' object has no attribute 'parent'
```

"force armature" import option being on or off results in the same error

**Comment by popos123** [comment]
i was fixed importing issue in new pull request, but still some models have problem with animations, i dont know why, maybe @taniwha know why, some parts when importing haves problem with armature and bones ... i was checked your parts and some armature isnt load correctly, but at least now is loading
